FROM phpmyadmin/phpmyadmin:edge-4.9

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>"

# Add volume for sessions to allow session persistence
VOLUME /sessions

#COPY themes/metro/ /etc/phpmyadmin/themes/metro/


# We expose phpMyAdmin on port 80
EXPOSE 80
